import { Product, Category } from './types';


// Fallback data - will be used if JSON loading fails
const FALLBACK_CATEGORIES: Category[] = [
  { id: 'dates', name: 'খেজুর ও ফল', icon: '🌴' },
  { id: 'iftar', name: 'ইফতার সামগ্রী', icon: '🍱' },
  { id: 'sehri', name: 'সেহরি আইটেম', icon: '🍚' },
  { id: 'islamic', name: 'ইসলামিক পণ্য', icon: '🕌' },
  { id: 'drinks', name: 'শরবত ও পানীয়', icon: '🥤' },
];

const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'মরিয়ম খেজুর (১ কেজি)',
    category: 'dates',
    price: 1200,
    image: '/images/marium-khejur_compressed.webp',
    description: 'উন্নত মানের সৌদি মরিয়ম খেজুর। রমজানে ইফতারের জন্য সেরা পছন্দ।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 2,
    name: 'আজওয়া খেজুর প্রিমিয়াম',
    category: 'dates',
    price: 1500,
    image: '/images/black-khejur_compressed.webp',
    description: 'মদিনার বিখ্যাত আজওয়া খেজুর। সুস্বাদু এবং পুষ্টিকর।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 3,
    name: 'রুহ আফজা (৭৫০ মিলি)',
    category: 'drinks',
    price: 450,
    image: '/images/roapja_compressed.webp',
    description: 'ইফতারের ক্লান্তি দূর করতে রুহ আফজা।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 4,
    name: 'স্পেশাল হালিম মিক্স',
    category: 'iftar',
    price: 120,
    image: '/images/halim_compressed.webp',
    description: 'দ্রুত এবং সুস্বাদু হালিম তৈরির জন্য সেরা মিক্স।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 5,
    name: 'জায়নামাজ (তুর্কি)',
    category: 'islamic',
    price: 850,
    image: '/images/jaynamaz_compressed.webp',
    description: 'নরম এবং আরামদায়ক তুর্কি জায়নামাজ।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 6,
    name: 'তসবিহ (ক্রিস্টাল)',
    category: 'islamic',
    price: 250,
    image: '/images/tosbi_compressed.webp',
    description: 'সুন্দর ডিজাইনের ক্রিস্টাল তসবিহ।',
    isPopular: false,
    isNew: false,
    stock: 10,
  },
  {
    id: 7,
    name: 'চিনিগুড়া চাল (৫ কেজি)',
    category: 'sehri',
    price: 650,
    image: '/images/cinigura-chal_compressed.webp',
    description: 'সুগন্ধি চিনিগুড়া চাল, বিরিয়ানি বা পোলাওয়ের জন্য।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 8,
    name: 'খাটি সরিষার তেল (১ লিটার)',
    category: 'sehri',
    price: 320,
    image: '/images/khati-sorisha_compressed.webp',
    description: 'ঘানি ভাঙা খাটি সরিষার তেল।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 9,
    name: 'মেহেরাব খেজুর (প্যাকেট)',
    category: 'dates',
    price: 800,
    image: '/images/khejur_compressed.webp',
    description: 'মধ্যপ্রাচ্য থেকে আমদানিকৃত মেহেরাব খেজুর।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 10,
    name: 'বরই (১ কেজি)',
    category: 'dates',
    price: 280,
    image: '/images/boroi_compressed.webp',
    description: 'তাজা বরই, ভিটামিন সি সমৃদ্ধ।',
    isPopular: false,
    isNew: false,
    stock: 10,
  },
  {
    id: 11,
    name: 'পেয়ারা জুস (১ লিটার)',
    category: 'drinks',
    price: 180,
    image: '/images/peyara-jush_compressed.webp',
    description: 'প্রাকৃতিক পেয়ারা জুস।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 12,
    name: 'ডিম (১২ পিস)',
    category: 'sehri',
    price: 160,
    image: '/images/dim_compressed.webp',
    description: 'তাজা দেশি মুরগির ডিম।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 13,
    name: 'পেঁয়াজু মিক্স',
    category: 'iftar',
    price: 95,
    image: '/images/peyaji-mix_compressed.webp',
    description: 'সহজে পেঁয়াজু বানানোর জন্য রেডিমেড মিক্স।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 14,
    name: 'জিলাপি (১ কেজি)',
    category: 'iftar',
    price: 420,
    image: '/images/jilapi_compressed.webp',
    description: 'মিষ্টি এবং সুস্বাদু জিলাপি।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 15,
    name: 'কুরআন শরীফ (বাংলা অনুবাদ)',
    category: 'islamic',
    price: 550,
    image: '/images/Quran-Sharif_compressed.webp',
    description: 'বাংলা অনুবাদসহ কুরআন শরীফ।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 16,
    name: 'আতর (৬ মিলি)',
    category: 'islamic',
    price: 380,
    image: '/images/ator_compressed.webp',
    description: 'আরবি আতর।',
    isPopular: false,
    isNew: true,
    stock: 10,
  },
  {
    id: 17,
    name: 'দুধ (১ লিটার)',
    category: 'drinks',
    price: 85,
    image: '/images/milk_compressed.webp',
    description: 'তাজা পাস্তুরিত দুধ।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
  {
    id: 18,
    name: 'ছোলা বুট (১ কেজি)',
    category: 'iftar',
    price: 110,
    image: '/images/sola-but_compressed.webp',
    description: 'ইফতারের জন্য ছোলা বুট।',
    isPopular: true,
    isNew: false,
    stock: 10,
  },
];

export const CATEGORIES: Category[] = FALLBACK_CATEGORIES;
export const PRODUCTS: Product[] = FALLBACK_PRODUCTS;
